# Generated by Django 4.1.2 on 2022-11-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descripion',
            new_name='description',
        ),
    ]
